### PR TITLE
Devel/mavros integration

### PR DESCRIPTION
**Pull request by potaito**

### CODE REVIEW

**Comment by potaito** [comment]
That was supposed to go into my fork, sorry

**Comment by rkintada** [comment]
HI potatio, I would like to take a look at the changes and see if we can main-line into this repo as well so that it will be easy to keep it in sync.  I will review these changes and let you know.

Thanks
Rama.

**Comment by potaito** [comment]
I am all in favour of that, so let me if I can be of help. This pull request here of course should not be merged as I replaced components in the VISLAM example instead of adding the ROS parts on top. 

There are a few issues / things to be taken care of: 
1. The CPU load is twice as high as with the original VISLAM example (on average two cores at 50% instead of just one). I can't believe it's all because of mavros.
2. It might make sense to not only fuse the pose estimate from VISLAM, but also the velocity to the PX4. This should provide a smoother estimate on the PX4 side. I [tried adding a twist publisher](https://github.com/potaito/snapdragon_mavros_vislam/commit/13b8381292a4ae4ceed741c46c37541306c141d6) for mavros, but could not verify that it's actually being fused by the LPE.
3. Since I set the mavros timesync mode to `PASSTHROUGH`, the IMU, Camera and VISLAM odometry messages have a timestamp relative to the boot time rather than the actual wall time (i.e. `ros::Time::now()`.

**Comment by rkintada** [comment]
@potaito thanks for willing to help.  After reviewing the code, I think there may be some changes to the framework that will help wtih cleaner integration.  In terms of the plan, this is what I am thinking of:

1) Update the VISLAM Manager to add an API to get the IMU data.  Also remove the dependency of IMU manager on VISLAM Manager.  By doing this, for px4 integration, one use mavRos to get the IMU an call the new API to inject the IMU data.
2) Update the make file/cmake file to create an new target for px4 integration. 

Question regarding one of the change you make to package.xml, does it need to change or can we make it generic but use a different launch file when integrating with px4.

Comment regarding the load increase, I am wondering if that is comming from px4 running on apps processor.  Can you run a test without VISLAM and see if the load is increased.

**Comment by potaito** [comment]
@rkintada 

> Update the VISLAM Manager to add an API to get the IMU data. Also remove the dependency of IMU manager on VISLAM Manager.

That sounds good. The IMU manager dependency was actually a bit confusing. 

> Question regarding one of the change you make to package.xml, does it need to change or can we make it generic but use a different launch file when integrating with px4.

No I do not think the change is crucial. Without mavros compiled or installed, the mavros-specific launch file would fail anyway.

> Comment regarding the load increase, I am wondering if that is comming from px4 running on apps processor. Can you run a test without VISLAM and see if the load is increased.

That's a very good point. 
- Running the original px4 stack with EKF2 results in one core being under approx. 15% load.  
- Running the px4 stack modified for LPE requires 30% of one core. 
- Running the original (EKF2) px4 stack with mavros and vislam: 2 cores at 50%
- Running PX4 with LPE, together with mavros and vislam: 2 - 3 cores at 50%

What I get from this is that there are two problems: One related to the modified `px4.config` and `mainapp.conf. Another one related to a change in the VISLAM package.

**Pull request closed without merging**
